# Learn more about this
# https://www.netlify.com/docs/netlify-toml-reference/

[[redirects]]
  from = "/blog/*"
  to = "/articles/blog/:splat"
  status = 200

[[redirects]]
  from = "/signatures/*"
  to = "/images/signatures/:splat"
  status = 200

[[redirects]]
  from = "/blog/*"
  to = "/error"
  status = 404

[[redirects]]
  from = "/blog/*/*"
  to = "/error"
  status = 404

[[redirects]]
  from = "/*"
  to = "/error"
  status = 404